trigger:
  branches:
    include:
    - release/2.2
  paths:
    include:
    - src/SiteExtensions

name: $(Date:yyMMdd)-$(Rev:rr)

phases:
- phase: SiteExtensions
  variables:
    CI: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    # This variable is required by MicroBuildSigningPlugin to determine permissions for codesigning.
    TeamName: AspNetCore

    # SignType = { test, real }
    # This is prefixed underscore because variables automatically become environment variables (and therefore MSBuild properties),
    # and this one was causing issues in MSBuild projects which use the $(SignType) MSbuild prop.
    _SignType: real

  steps:
  - task: MicroBuildSigningPlugin@1
    displayName: Install MicroBuild plugin
    condition: and(succeeded(), in(variables['_SignType'], 'test', 'real'))
    inputs:
      signType: $(_SignType)
      zipSources: false
  - script: src/SiteExtensions/LoggingAggregate/build.cmd -ci
    displayName: Run src/SiteExtensions/LoggingAggregate/build.cmd
  - task: PublishBuildArtifacts@1
    displayName: Upload artifacts
    condition: eq(variables['system.pullrequest.isfork'], false)
    inputs:
      pathtoPublish: ./src/SiteExtensions/LoggingAggregate/artifacts/
      artifactName: artifacts-Windows-Release
      artifactType: Container
  - task: MicroBuildCleanup@1
    displayName: Cleanup MicroBuild tasks
    condition: always()
