jobs:
- template: default-build.yml
  parameters:
    buildScript: ./build.cmd
    buildArgs: "-ci -restore -build -test -projects src/Servers/IIS/**/*.csproj ${{ parameters.skipArgs }}"
    beforeBuild:
      - powershell: "& ./src/Servers/IIS/tools/UpdateIISExpressCertificate.ps1; & ./src/Servers/IIS/tools/update_schema.ps1; & ./src/Servers/IIS/tools/SetupTestEnvironment.ps1 Setup"
        displayName: Prepare repo
    afterBuild:
      - powershell: "& ./src/Servers/IIS/tools/SetupTestEnvironment.ps1 Shutdown"
        displayName: Stop AppVerifier
        condition: always()
    jobName: ANCM_${{ parameters.TestGroupName }}
    jobDisplayName: "Build and test: ANCM ${{ parameters.TestGroupName }}"
